#!/bin/sh

origin_name="$(git remote | head -1)"
current_remote_url="$(git config --get --local remote.$origin_name.url)"
default_name="$(git config --get user.name)"
default_email="$(git config --get user.email)"
local_name="$(git config --local --get user.name)"
local_email="$(git config --local --get user.email)"
config_changed=

echo $current_remote_url

if [ "$current_remote_url" ]; then
    case $current_remote_url in
        *://*)
            # Normalize URL: remove leading "git+"
            #   e.g. "git+ssh://user@host/path/" ==> "ssh://user@host/path/"
            current_remote_url=$(echo $current_remote_url | sed 's/^git\+//')
            ;;
        *:*)
            # Convert scp-style URL to normal-form
            #   e.g. "user@host:path/" ==> "ssh://user@host/path/"
            current_remote_url=$(echo $current_remote_url | sed 's/\(.*\):/ssh:\/\/\1\//')
            ;;
    esac
    if [ -z "$local_name" ]; then
        name="$(git config --get-urlmatch user.name $current_remote_url)"
        if [ "$name" != "$default_name" ]; then
            git config --local user.name "$name"
            echo "Set `git config` automatically: user.name=$name"
            config_changed=1
        fi
    fi
    if [ -z "$local_email" ]; then
        email="$(git config --get-urlmatch user.email $current_remote_url)"
        if [ "$email" != "$default_email" ]; then
            git config --local user.email "$email"
            echo "Seta `git config` automatically: user.email=$email"
            config_changed=1
        fi
    fi
fi
if [ -n "$config_changed" ] ; then
    echo "Aborted."
    exit 1
fi
